# Makefile to Rebuild Projects

help:
	@echo "Help message:"
	@echo "  help   -  show this help message"
	@echo "  build  -  to build webapp to cdn version"
	@echo "  clean  -  to remove all static files built by montanus"

build:
	montanus build

clean:
	rm -rf ./*.* 

